spring:
  datasource:
    url: jdbc:postgresql://dpg-d86qac8jo89c73eedm90-a.frankfurt-postgres.render.com:5432/postgre_bbdd_obzf?sslmode=require
    username: postgre_bbdd_user
    password: hFvW5bsDBPusPlE5b6OU0Yvq1MxQPJi7
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
