spring:
  datasource:
    url: jdbc:postgresql://dpg-d80p7lrrjlhs73ahhdpg-a.frankfurt-postgres.render.com:5432/postgre_bbdd?sslmode=require
    username: postgre_bbdd_user
    password: B4njRTMp6QYawguaBcn9mKok0x01lvv5
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
